//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmourClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArmourClass()
        {
            this.ArmourTypes = new HashSet<ArmourType>();
            this.ClassArmourProficienciesBridges = new HashSet<ClassArmourProficienciesBridge>();
        }
    
        public int ArmourClassId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ArmourWeightClassId { get; set; }
    
        public virtual ArmourWeightClass ArmourWeightClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArmourType> ArmourTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassArmourProficienciesBridge> ClassArmourProficienciesBridges { get; set; }
    }
}
