//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmourType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArmourType()
        {
            this.ArmourItems = new HashSet<ArmourItem>();
        }
    
        public int ArmourTypeId { get; set; }
        public Nullable<int> ArmourClassId { get; set; }
        public string Name { get; set; }
        public int Bonus { get; set; }
        public int MinEnchantmentBonus { get; set; }
        public int CheckPenalty { get; set; }
        public int SpeedPenalty { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int WeightPounds { get; set; }
    
        public virtual ArmourClass ArmourClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArmourItem> ArmourItems { get; set; }
    }
}
