//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class LightSource
    {
        public int LightSourceId { get; set; }
        public string Name { get; set; }
        public int Radius { get; set; }
        public string Brightness { get; set; }
        public int Duration { get; set; }
    }
}
