//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MapArea()
        {
            this.Actors = new HashSet<Actor>();
            this.GameMapAreasBridges = new HashSet<GameMapAreasBridge>();
            this.MapAreas1 = new HashSet<MapArea>();
        }
    
        public int MapAreaId { get; set; }
        public int MapAreaTypeId { get; set; }
        public string Name { get; set; }
        public string FlavourText { get; set; }
        public Nullable<int> ShopId { get; set; }
        public byte[] MapImage { get; set; }
        public Nullable<int> ParentMapAreaId { get; set; }
        public Nullable<decimal> ParentMapAreaLocationN { get; set; }
        public Nullable<decimal> ParentMapAreaLocationE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameMapAreasBridge> GameMapAreasBridges { get; set; }
        public virtual MapAreaType MapAreaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapArea> MapAreas1 { get; set; }
        public virtual MapArea MapArea1 { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
