//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonPlayerCharacter
    {
        public int NonPlayerCharacterId { get; set; }
        public int ActorId { get; set; }
        public string Name { get; set; }
        public int CombatLevel { get; set; }
        public int ClassId { get; set; }
        public int RaceId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Height { get; set; }
        public Nullable<int> WeightPounds { get; set; }
        public int AlignmentId { get; set; }
        public Nullable<int> DeityId { get; set; }
        public int HitPoints { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Alignment Alignment { get; set; }
        public virtual Class Class { get; set; }
        public virtual Deity Deity { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Race Race { get; set; }
    }
}
