//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purse
    {
        public int PurseId { get; set; }
        public int OwnerActorId { get; set; }
        public int CopperPieces { get; set; }
        public int SilverPieces { get; set; }
        public int GoldPieces { get; set; }
        public int Platinum { get; set; }
        public int AstralDiamonds { get; set; }
    
        public virtual Actor Actor { get; set; }
    }
}
