//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.MapAreas = new HashSet<MapArea>();
        }
    
        public int ShopId { get; set; }
        public string Name { get; set; }
        public int OwnerActorId { get; set; }
        public decimal CostModifier { get; set; }
        public bool SellsMagicItems { get; set; }
        public string FlavourText { get; set; }
    
        public virtual Actor Actor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MapArea> MapAreas { get; set; }
    }
}
