//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weapon()
        {
            this.WeaponPropertiesBridges = new HashSet<WeaponPropertiesBridge>();
        }
    
        public int WeaponId { get; set; }
        public int WeaponCategoryId { get; set; }
        public int AttackClassId { get; set; }
        public int Handedness { get; set; }
        public int ProficiencyBonus { get; set; }
        public int DamageNumDice { get; set; }
        public int DamageDieSides { get; set; }
        public Nullable<int> NormalRange { get; set; }
        public Nullable<int> LongRange { get; set; }
        public decimal Cost { get; set; }
        public int WeightPounds { get; set; }
        public int WeaponGroupId { get; set; }
        public Nullable<int> OwnerActorId { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual AttackClass AttackClass { get; set; }
        public virtual WeaponCategory WeaponCategory { get; set; }
        public virtual WeaponGroup WeaponGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeaponPropertiesBridge> WeaponPropertiesBridges { get; set; }
    }
}
