//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbilityValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbilityValue()
        {
            this.Prerequisites = new HashSet<Prerequisite>();
        }
    
        public int AbilityValueId { get; set; }
        public Nullable<int> ActorId { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public int AbilityId { get; set; }
        public int Modifier { get; set; }
    
        public virtual Ability Ability { get; set; }
        public virtual Actor Actor { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Race Race { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisite> Prerequisites { get; set; }
    }
}
