//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArmourItem
    {
        public int ArmourItemId { get; set; }
        public Nullable<int> ArmourTypeId { get; set; }
        public Nullable<int> OwnerActorId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsMagic { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual ArmourType ArmourType { get; set; }
    }
}
