//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassWeaponProficienciesBridge
    {
        public int ClassWeaponProficiencyId { get; set; }
        public int ClassId { get; set; }
        public int AttackClassId { get; set; }
    
        public virtual AttackClass AttackClass { get; set; }
        public virtual Class Class { get; set; }
    }
}
