//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ClassArmourProficienciesBridges = new HashSet<ClassArmourProficienciesBridge>();
            this.ClassFeaturesBridges = new HashSet<ClassFeaturesBridge>();
            this.ClassImplementProficienciesBridges = new HashSet<ClassImplementProficienciesBridge>();
            this.ClassPowersBridges = new HashSet<ClassPowersBridge>();
            this.ClassTrainedSkillsBridges = new HashSet<ClassTrainedSkillsBridge>();
            this.ClassWeaponProficienciesBridges = new HashSet<ClassWeaponProficienciesBridge>();
            this.DefenseModifiers = new HashSet<DefenseModifier>();
            this.ParagonPaths = new HashSet<ParagonPath>();
            this.PlayerCharacters = new HashSet<PlayerCharacter>();
            this.Prerequisites = new HashSet<Prerequisite>();
        }
    
        public int ClassId { get; set; }
        public string Name { get; set; }
        public int RoleId { get; set; }
        public int PowerSourceId { get; set; }
        public int BaseHitPoints { get; set; }
        public Nullable<int> BaseHitPointsAbilityId { get; set; }
        public int HitPointsPerLevel { get; set; }
        public int HealingSurges { get; set; }
        public Nullable<int> HealingSurgesAbilityId { get; set; }
        public string FlavourText { get; set; }
    
        public virtual Ability Ability { get; set; }
        public virtual Ability Ability1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassArmourProficienciesBridge> ClassArmourProficienciesBridges { get; set; }
        public virtual PowerSource PowerSource { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassFeaturesBridge> ClassFeaturesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassImplementProficienciesBridge> ClassImplementProficienciesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassPowersBridge> ClassPowersBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassTrainedSkillsBridge> ClassTrainedSkillsBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassWeaponProficienciesBridge> ClassWeaponProficienciesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefenseModifier> DefenseModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParagonPath> ParagonPaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCharacter> PlayerCharacters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisite> Prerequisites { get; set; }
    }
}
