//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTrainedSkillsBridge
    {
        public int ClassTrainedSkillId { get; set; }
        public int ClassId { get; set; }
        public int SkillId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
