//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DungeonsAndDragonsEntities : DbContext
    {
        public DungeonsAndDragonsEntities()
            : base("name=DungeonsAndDragonsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Abilities { get; set; }
        public virtual DbSet<AbilityValue> AbilityValues { get; set; }
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<ActorType> ActorTypes { get; set; }
        public virtual DbSet<Alignment> Alignments { get; set; }
        public virtual DbSet<ArmourClass> ArmourClasses { get; set; }
        public virtual DbSet<ArmourItem> ArmourItems { get; set; }
        public virtual DbSet<ArmourType> ArmourTypes { get; set; }
        public virtual DbSet<ArmourWeightClass> ArmourWeightClasses { get; set; }
        public virtual DbSet<AttackClass> AttackClasses { get; set; }
        public virtual DbSet<AttackType> AttackTypes { get; set; }
        public virtual DbSet<AuthorityLevel> AuthorityLevels { get; set; }
        public virtual DbSet<ClassArmourProficienciesBridge> ClassArmourProficienciesBridges { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassFeaturesBridge> ClassFeaturesBridges { get; set; }
        public virtual DbSet<ClassImplementProficienciesBridge> ClassImplementProficienciesBridges { get; set; }
        public virtual DbSet<ClassPowersBridge> ClassPowersBridges { get; set; }
        public virtual DbSet<ClassTrainedSkillsBridge> ClassTrainedSkillsBridges { get; set; }
        public virtual DbSet<ClassWeaponProficienciesBridge> ClassWeaponProficienciesBridges { get; set; }
        public virtual DbSet<CompassionLevel> CompassionLevels { get; set; }
        public virtual DbSet<ConsumableItem> ConsumableItems { get; set; }
        public virtual DbSet<DamageType> DamageTypes { get; set; }
        public virtual DbSet<DefenseModifier> DefenseModifiers { get; set; }
        public virtual DbSet<Defens> Defenses { get; set; }
        public virtual DbSet<Deity> Deities { get; set; }
        public virtual DbSet<DurationUnit> DurationUnits { get; set; }
        public virtual DbSet<EffectType> EffectTypes { get; set; }
        public virtual DbSet<EpicDestiny> EpicDestinies { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<GameActorsBridge> GameActorsBridges { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GearItem> GearItems { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<ImplementType> ImplementTypes { get; set; }
        public virtual DbSet<LanguageRacesBridge> LanguageRacesBridges { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LightSource> LightSources { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<ParagonPath> ParagonPaths { get; set; }
        public virtual DbSet<PlayerCharacterFeaturesBridge> PlayerCharacterFeaturesBridges { get; set; }
        public virtual DbSet<PlayerCharacterLanguagesBridge> PlayerCharacterLanguagesBridges { get; set; }
        public virtual DbSet<PlayerCharacter> PlayerCharacters { get; set; }
        public virtual DbSet<PowerEffectsBridge> PowerEffectsBridges { get; set; }
        public virtual DbSet<Power> Powers { get; set; }
        public virtual DbSet<PowerSource> PowerSources { get; set; }
        public virtual DbSet<PowerUsage> PowerUsages { get; set; }
        public virtual DbSet<Prerequisite> Prerequisites { get; set; }
        public virtual DbSet<Purse> Purses { get; set; }
        public virtual DbSet<RaceFeaturesBridge> RaceFeaturesBridges { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Script> Scripts { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<SkillModifier> SkillModifiers { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<TargetType> TargetTypes { get; set; }
        public virtual DbSet<TransportItem> TransportItems { get; set; }
        public virtual DbSet<VisionLevel> VisionLevels { get; set; }
        public virtual DbSet<WeaponCategory> WeaponCategories { get; set; }
        public virtual DbSet<WeaponGroup> WeaponGroups { get; set; }
        public virtual DbSet<WeaponProperty> WeaponProperties { get; set; }
        public virtual DbSet<WeaponPropertiesBridge> WeaponPropertiesBridges { get; set; }
        public virtual DbSet<Weapon> Weapons { get; set; }
    }
}
