//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefenseModifier
    {
        public int DefenseModifierId { get; set; }
        public Nullable<int> ActorId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public Nullable<int> RaceId { get; set; }
        public int DefenseId { get; set; }
        public int Modifier { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Class Class { get; set; }
        public virtual Defens Defens { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual Race Race { get; set; }
    }
}
