//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feature()
        {
            this.AbilityValues = new HashSet<AbilityValue>();
            this.ClassFeaturesBridges = new HashSet<ClassFeaturesBridge>();
            this.DefenseModifiers = new HashSet<DefenseModifier>();
            this.PlayerCharacterFeaturesBridges = new HashSet<PlayerCharacterFeaturesBridge>();
            this.Prerequisites = new HashSet<Prerequisite>();
            this.Prerequisites1 = new HashSet<Prerequisite>();
            this.RaceFeaturesBridges = new HashSet<RaceFeaturesBridge>();
            this.SkillModifiers = new HashSet<SkillModifier>();
        }
    
        public int FeatureId { get; set; }
        public string Name { get; set; }
        public string TextDescription { get; set; }
        public Nullable<int> InitiativeModifier { get; set; }
        public Nullable<int> HitPointModifier { get; set; }
        public Nullable<int> HealingSurgesModifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbilityValue> AbilityValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassFeaturesBridge> ClassFeaturesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefenseModifier> DefenseModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCharacterFeaturesBridge> PlayerCharacterFeaturesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisite> Prerequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisite> Prerequisites1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceFeaturesBridge> RaceFeaturesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillModifier> SkillModifiers { get; set; }
    }
}
