//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerCharacter()
        {
            this.PlayerCharacterFeaturesBridges = new HashSet<PlayerCharacterFeaturesBridge>();
            this.PlayerCharacterLanguagesBridges = new HashSet<PlayerCharacterLanguagesBridge>();
        }
    
        public int PlayerCharacterId { get; set; }
        public int ActorId { get; set; }
        public int ActorTypeId { get; set; }
        public string Name { get; set; }
        public int CombatLevel { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> ParagonPathId { get; set; }
        public Nullable<int> EpicDestinyId { get; set; }
        public int ExperiencePoints { get; set; }
        public int RaceId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Height { get; set; }
        public Nullable<int> WeightPounds { get; set; }
        public int AlignmentId { get; set; }
        public Nullable<int> DeityId { get; set; }
        public int Initiative { get; set; }
        public int PassiveInsight { get; set; }
        public int PassivePerception { get; set; }
        public int HitPoints { get; set; }
        public int BaseActionPoints { get; set; }
        public Nullable<int> AdditionalActionPoints { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Alignment Alignment { get; set; }
        public virtual Class Class { get; set; }
        public virtual Deity Deity { get; set; }
        public virtual EpicDestiny EpicDestiny { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ParagonPath ParagonPath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCharacterFeaturesBridge> PlayerCharacterFeaturesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCharacterLanguagesBridge> PlayerCharacterLanguagesBridges { get; set; }
        public virtual Race Race { get; set; }
    }
}
