//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCharacterFeaturesBridge
    {
        public int PlayerCharacterFeatureId { get; set; }
        public int PlayerCharacterId { get; set; }
        public int FeatureId { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual PlayerCharacter PlayerCharacter { get; set; }
    }
}
