//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonsAndDragons_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Race()
        {
            this.AbilityValues = new HashSet<AbilityValue>();
            this.DefenseModifiers = new HashSet<DefenseModifier>();
            this.LanguageRacesBridges = new HashSet<LanguageRacesBridge>();
            this.PlayerCharacters = new HashSet<PlayerCharacter>();
            this.Prerequisites = new HashSet<Prerequisite>();
            this.RaceFeaturesBridges = new HashSet<RaceFeaturesBridge>();
            this.SkillModifiers = new HashSet<SkillModifier>();
        }
    
        public int RaceId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> VisionLevelId { get; set; }
        public bool IsPlayable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbilityValue> AbilityValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefenseModifier> DefenseModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LanguageRacesBridge> LanguageRacesBridges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCharacter> PlayerCharacters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prerequisite> Prerequisites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceFeaturesBridge> RaceFeaturesBridges { get; set; }
        public virtual Size Size { get; set; }
        public virtual VisionLevel VisionLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkillModifier> SkillModifiers { get; set; }
    }
}
